@startuml dicom_sr_measurement_report_mapping_overview
skinparam componentStyle rectangle
allowmixing
left to right direction
package "DICOM SR Measurement Report" as measurementReport {
    package "Document IE" as documentIE {
        package "SR Content Sequence" as srContentSequence {
            package "Imaging Measurements Container" as imagingMeasurementsContainer {
                package "0..* Measurements Group" as measurementsGroup {
                    object "0..* Numerical Measurement" as numericalMeasurement
                    object "0..* Qualitative Evaluation" as measurementGroupQualitativeEvaluation
                }
                package "0..* Derived Imaging Measurements" as derivedImagingMeasurements {
                    object "0..* Measurements Group" as derivedMeasurementsGroup
                }
                package "Qualitative Evaluations" as qualitativeEvaluations {
                    object "0..* Qualitative Evaluation" as qualitativeEvaluation
                }
            }
        }
    }
}

component "[[mapping.html#sr_instance DICOM SR Measurement Report Instance Mapping]]" as measurementReportInstanceMapping
component "[[mapping.html#sr_document Document IE Mapping]]" as documentIEMapping
component "[[mapping.html#imaging_measurements_container Imaging Measurements Container Mapping]]" as imagingMeasurementsContainerMapping
component "[[mapping.html#imaging_measurement_group Imaging Measurements Group Mapping]]" as imagingMeasurementGroupMapping
component "[[mapping.html#imaging_measurement Imaging Measurement Mapping]]" as imagingMeasurementMapping
component "[[mapping.html#qualitative_evaluation Qualitative Evaluation Mapping]]" as qualitativeEvaluationMapping
component "[[mapping.html#derived_imaging_measurements Derived Imaging Measurements Mapping]]" as derivedImagingMeasurementsMapping

measurementReport --> measurementReportInstanceMapping: Map contents of Measurement Report Instance
documentIE --> documentIEMapping: Map contents of Document IE
imagingMeasurementsContainer --> imagingMeasurementsContainerMapping: Map contents of Imaging Measurements Container
measurementsGroup --> imagingMeasurementGroupMapping: Map contents of Measurements Group
numericalMeasurement --> imagingMeasurementMapping: Map contents of Imaging Measurement
measurementGroupQualitativeEvaluation --> qualitativeEvaluationMapping: Map contents of Qualitative Evaluation
derivedImagingMeasurements --> derivedImagingMeasurementsMapping: Map contents of Derived Imaging Measurements
derivedMeasurementsGroup --> imagingMeasurementGroupMapping: Map contents of Measurements Group
qualitativeEvaluation --> qualitativeEvaluationMapping: Map contents of Qualitative Evaluation

@enduml