@startuml dicom_sr_document_ie_mapping
left to right direction

map "[[mapping.html#sr_instance Inputs from DICOM SR Measurement Report Instance Mapping]]" as inputs {
    subject => Patient
    partOf => ImagingStudy
    basedOn => ServiceRequest
    device => EquipmentDevice
}

package "Document IE" {
    object documentGeneralModule {
        PreliminaryFlag
        ParticipantSequence
    }
    package "SR Content Sequence" as srContentSequence {
        object "Imaging Measurements Container" as imagingMeasurements
    }
}

map "[[mapping.html#imaging_measurements_container Imaging Measurements Container Mapping]]" as imagingMeasurementsMapping {
    subject => Patient
    partOf => ImagingStudy
    basedOn => ServiceRequest
    device => EquipmentDevice or ParticipantSequence (Device)
    performer => ParticipantSequence (Person)
    status => PreliminaryFlag
}

imagingMeasurements --> imagingMeasurementsMapping: Map contents of Imaging Measurements Container
inputs --> imagingMeasurementsMapping
documentGeneralModule --> imagingMeasurementsMapping
@enduml