@startuml imaging_measurement_group_mapping
left to right direction

map "[[mapping.html#imaging-measurements-container-mapping Inputs from Imaging Measurements Container Mapping]]" as inputs {
   subject => Patient
   partOf => ImagingStudy
   basedOn => ServiceRequest
   device => EquipmentDevice
}

package "Measurements Group" as measurementGroup {
   object "Algorithm Identification" as algorithm
   object "Tracking Identifier / UID" as tracking
   object "Finding" as finding
   object "Finding Category" as findingCategory
   object "Finding Site" as BodyStructureFindingSite
   object "Image Region / Reference" as imageRegion
   object "Measurement Method" as method
   package "Numerical Measurements" {
    object "Numerical Measurement" as measurement
   }
}

object "Device - AlgorithmIdentification" as AlgorithmIdentification {
    parent = EquipmentDevice
}

object "Body Structure - BodyStructureTrackingIdentifiers" as TrackingBodyStructure {
    identifier = TrackingID or TrackingUID
}

object "Body Structure - BodyStructureFindingSite" as BodyStructureFindingSite {
    includedStructure.structure = Finding Site
    includedStrucutre.laterality = Laterality
    includedStructure.qualifier = Topographical modifier
}

object ImagingSelection 

object "Observation - Imaging Measurement Group" as imagingMeasurementGroup {
    subject = Patient
    partOf = ImagingStudy
    basedOn = ServiceRequest
    device = EquipmentDevice or AlgorithmIdentification
    focus = BodyStructureTrackingIdentifiers
    focus = ImagingSelection
    bodyStructure = BodyStructureFindingSite
    code = Finding Category or DCM#125007 "Measurement Group"
    method = Measurement Method
    valueCodeableConcept = Finding
    hasMember = ImagingMeasurement
}

map "[[mapping.html#imaging-measurement-mapping Imaging Measurement Mapping]]" as imagingMeasurementMap {
    subject => Patient
    partOf => ImagingStudy
    basedOn => ServiceRequest
    focus => TrackingBodyStructure
    focus => ImagingSelection
    bodyStructure => BodyStructureFindingSite
    device => AlgorithmIdentification or EquipmentDevice
}

algorithm --> AlgorithmIdentification: Create AlgorithmIdentification from Algorithm Identification content item
tracking --> TrackingBodyStructure: Create BodyStructure reference from Tracking Identifier / UID
BodyStructureFindingSite --> BodyStructureFindingSite: Create BodyStructure from Finding Site
imageRegion --> ImagingSelection: Create ImagingSelection from image reference or region

inputs --> imagingMeasurementGroup
AlgorithmIdentification --> imagingMeasurementGroup
TrackingBodyStructure --> imagingMeasurementGroup
finding --> imagingMeasurementGroup
findingCategory --> imagingMeasurementGroup
BodyStructureFindingSite --> imagingMeasurementGroup
ImagingSelection --> imagingMeasurementGroup
measurementGroup --> imagingMeasurementGroup
method --> imagingMeasurementGroup

inputs --> imagingMeasurementMap
measurement --> imagingMeasurementMap: Map numerical measurements to ImagingMeasurement Observations
imagingMeasurementMap <-- imagingMeasurementGroup: hasMember
@enduml