@startuml architecture
left to right direction

abstract class "Imaging Measurement" as ImagingMeasurementCore <<Observation>> #d5e8d4 ##[dashed]green
class "TID 1410 Planar ROI Measurement Group" as PlanarMeasurementGroup <<Observation>> #d5e8d4 ##green
class "TID 1411 Volumetric ROI Measurement Group" as VolumetricMeasurementGroup <<Observation>> #d5e8d4 ##green
class "TID 1500 Measurement and Qualitative Evaluation Group" as MeasurementGroup <<Observation>> #d5e8d4 ##green
class "TID 1420 Derived Measurement" as DerivedMeasurement <<Observation>> #d5e8d4 ##green
class "TID 1419 ROI Measurement" as ROIMeasurement <<Observation>> #d5e8d4 ##green
class "TID 300 Measurement" as Measurement <<Observation>> #d5e8d4 ##green
class "Qualitative Evaluation" as QualitativeEvaluation <<Observation>> #d5e8d4 ##green

class ImagingStudy #a3e7ff ##34b1eb
class Patient #a3e7ff ##34b1eb
class Practitioner #a3e7ff ##34b1eb
class Device #a3e7ff ##34b1eb
class ImagingSelection #a3e7ff ##34b1eb
class BodyStructure #a3e7ff ##34b1eb


package TID.1500.measurement.report #EEEEEE {
    package imaging.measurements {
    }
    package derived.imaging.measurements {
    }
    package qualitative.evaluations {
    }
}

.ImagingMeasurementCore <|-- PlanarMeasurementGroup
.ImagingMeasurementCore <|-- VolumetricMeasurementGroup
.ImagingMeasurementCore <|-- MeasurementGroup
.ImagingMeasurementCore <|-- DerivedMeasurement
.ImagingMeasurementCore <|-- QualitativeEvaluation
.ImagingMeasurementCore <|-- ROIMeasurement
.ImagingMeasurementCore <|-- Measurement

imaging.measurements --> PlanarMeasurementGroup : contains[0..*]
imaging.measurements --> VolumetricMeasurementGroup : contains[0..*]
imaging.measurements --> MeasurementGroup : contains[0..*]
derived.imaging.measurements --> DerivedMeasurement : contains[0..*]
qualitative.evaluations --> QualitativeEvaluation : contains[0..*]

PlanarMeasurementGroup --> ROIMeasurement : hasMember[0..*]
VolumetricMeasurementGroup --> ROIMeasurement : hasMember[0..*]
MeasurementGroup --> Measurement : hasMember[0..*]

DerivedMeasurement --> PlanarMeasurementGroup : XOR derivedFrom[0..*]
DerivedMeasurement --> VolumetricMeasurementGroup : XOR derivedFrom[0..*]

PlanarMeasurementGroup --> ImagingSelection : focus[0..*]
VolumetricMeasurementGroup --> ImagingSelection : focus[0..*]
MeasurementGroup --> ImagingSelection : focus[0..*]

ImagingMeasurementCore --> ImagingStudy : partOf[1..1]
ImagingMeasurementCore --> Patient : subject[1..1]
ImagingMeasurementCore --> Practitioner : performer[0..1]
ImagingMeasurementCore --> Device : device[0..1]
ImagingMeasurementCore --> BodyStructure: focus[0..1]



@enduml
