@startuml dicom_sr_measurement_report_structure
left to right direction
package "DICOM SR Measurement Report" as measurementReport {
    package "Document IE" as documentIE {
        package "SR Content Sequence" as srContentSequence {
            package "Imaging Measurements Container" as imagingMeasurementsContainer {
                package "0..* Measurements Group" as measurementsGroup {
                    object "0..* Numerical Measurement" as numericalMeasurement
                    object "0..* Qualitative Evaluation" as measurementGroupQualitativeEvaluation
                }
                package "0..* Derived Imaging Measurements" as derivedImagingMeasurements {
                    object "0..* Measurements Group" as derivedMeasurementsGroup
                }
                package "Qualitative Evaluations" as qualitativeEvaluations {
                    object "0..* Qualitative Evaluation" as qualitativeEvaluation
                }
            }
        }
    }
}

object "DICOM SR Measurement Report Instance Mapping" as measurementReportInstanceMapping
object "Document IE Mapping" as documentIEMapping
object "Imaging Measurements Container Mapping" as imagingMeasurementsContainerMapping
object "Imaging Measurements Group Mapping" as imagingMeasurementsGroupMapping
object "Imaging Measurements Mapping" as imagingMeasurementsMapping
object "Qualitative Evaluations Mapping" as qualitativeEvaluationsMapping
object "Derived Imaging Measurements Mapping" as derivedImagingMeasurementsMapping

measurementReport --> measurementReportInstanceMapping: Map contents of Measurement Report Instance
documentIE --> documentIEMapping: Map contents of Document IE
imagingMeasurementsContainer --> imagingMeasurementsContainerMapping: Map contents of Imaging Measurements Container
measurementsGroup --> imagingMeasurementsGroupMapping: Map contents of Measurements Group
numericalMeasurement --> imagingMeasurementsMapping: Map contents of Numerical Measurement
measurementGroupQualitativeEvaluation --> qualitativeEvaluationsMapping: Map contents of Qualitative Evaluation
derivedImagingMeasurements --> derivedImagingMeasurementsMapping: Map contents of Derived Imaging Measurements
derivedMeasurementsGroup --> imagingMeasurementsGroupMapping: Map contents of Measurements Group
qualitativeEvaluation --> qualitativeEvaluationsMapping: Map contents of Qualitative Evaluation

@enduml