@startuml dicom_sr_device
left to right direction

class "Equipment" as EquipmentDevice <<Device>> #d5e8d4 ##green
class "Measurement Group Algorithm" as MeasurementGroupDevice <<Device>> #d5e8d4 ##green
class "Measurement Algorithm" as MeasurementDevice <<Device>> #d5e8d4 ##green
class "Qualitative Evaluation Algorithm" as QualitativeDevice <<Device>> #d5e8d4 ##green

class "Imaging Measurement Group" as ImagingMeasurementGroup <<Observation>> #d5e8d4 ##green
class "Imaging Measurement" as ImagingMeasurement <<Observation>> #d5e8d4 ##green
class "Imaging Qualitative Evaluation" as ImagingQualitativeEvaluation <<Observation>> #d5e8d4 ##green
note "If Measurement Group Algorithm is not present device is Equipment." as MGNote
note "If Measurement Algorithm is not present device is Equipment." as MNote
note "If Qualitative Evaluation Algorithm is not present device is Equipment." as QENote

package DICOM.equipment.ie #EEEEEE {
    package DICOM.document.ie #EEEEEE {
        package TID.1500.measurement.report #EEEEEE {
            package CONTAINER.imaging.measurements {
                package 0..n.CONTAINER.imaging.measurement.group {
                    Object 0..n.imaging.measurement
                    Object 0..n.imaging.qualitative.evaluation
                    }
            }
            package CONTAINER.qualitative.evaluations {
                Object 0..n.qualitative.evaluation
            }
        }
    }
}

DICOM.equipment.ie --> EquipmentDevice: maps to

CONTAINER.imaging.measurements --> ImagingMeasurementGroup : contains[0..*]
CONTAINER.qualitative.evaluations --> ImagingQualitativeEvaluation : contains[0..*]

ImagingMeasurementGroup --> ImagingMeasurement : hasMember[0..*]
ImagingMeasurementGroup --> ImagingQualitativeEvaluation : hasMember[0..*]
ImagingMeasurementGroup --> MeasurementGroupDevice : device[1..1]
ImagingMeasurementGroup --> EquipmentDevice : device[1..1]
ImagingMeasurementGroup .. MGNote
MGNote .. MeasurementGroupDevice
MGNote .. EquipmentDevice


ImagingMeasurement --> MeasurementDevice : device[1..1]
ImagingMeasurement --> EquipmentDevice : device[1..1]
ImagingMeasurement .. MNote
MNote .. MeasurementDevice
MNote .. EquipmentDevice

ImagingQualitativeEvaluation --> QualitativeDevice : device[1..1]
ImagingQualitativeEvaluation --> EquipmentDevice : device[1..1]
ImagingQualitativeEvaluation .. QENote
QENote .. QualitativeDevice
QENote .. EquipmentDevice


MeasurementDevice --> EquipmentDevice : parent[1..1]

MeasurementGroupDevice --> EquipmentDevice : parent[1..1]

QualitativeDevice --> EquipmentDevice : parent[1..1]

@enduml
