@startuml dicom_sr_workflow
start
:Create Patient Reference from Patient IE; <<procedure>>
:Patient Reference; <<output>>
:Create ImagingStudy Reference from Study IE; <<procedure>>
:ImagingStudy Reference; <<output>>
:Create ServiceRequest Reference from Study IE; <<procedure>>
:ServiceRequest Reference; <<output>>
:Create EquipmentDevice from General Equipment IE; <<procedure>>
:EquipmentDevice; <<output>>
:Find Imaging Measurements Container; <<procedure>>
:Process Imaging Measurements Container; <<procedure>>
partition "Inputs" {
    :Patient Reference; <<input>>
    :ImagingStudy Reference; <<input>>
    :ImagingStudy Reference; <<input>>
    :EquipmentDevice; <<input>>
}
end

@enduml