@startuml dicom_sr_device
left to right direction

class "Equipment" as EquipmentDevice <<Device>> #d5e8d4 ##green
class "Measurement Group Algorithm" as MeasurementGroupDevice <<Device>> #d5e8d4 ##green
class "Measurement Algorithm" as MeasurementDevice <<Device>> #d5e8d4 ##green
class "Qualitative Evaluation Algorithm" as QualitativeDevice <<Device>> #d5e8d4 ##green

class "Imaging Measurement Group" as ImagingMeasurementGroup <<Observation>> #d5e8d4 ##green
class "Imaging Measurement" as ImagingMeasurement <<Observation>> #d5e8d4 ##green
class "Imaging Qualitative Evaluation" as ImagingQualitativeEvaluation <<Observation>> #d5e8d4 ##green
note "If Measurement Group Algorithm is not present device is Equipment." as MGNote
note "If Measurement Algorithm is not present device is Equipment." as MNote
note "If Qualitative Evaluation Algorithm is not present device is Equipment." as QENote

package equipment_ie as "DICOM Equipment IE" #EEEEEE {
    package document_ie as "DICOM Document IE" #EEEEEE {
        package measurement_report as "TID 1500 Measurement Report" #EEEEEE {
            package imaging_measurements_container as "CONTAINER - Imaging Measurements" {
                package imaging_measurement_group as "0..n CONTAINER - Imaging Measurement Group" {
                    Object imaging_measurement
                    Object imaging_qualitative_evaluation
                    }
            }
            package qualitative_evaluations as "CONTAINER - Qualitative Evaluations" {
                Object qualitative_evaluation
            }
        }
    }
}

equipment_ie --> EquipmentDevice: maps to

imaging_measurements_container --> ImagingMeasurementGroup : contains[0..*]
qualitative_evaluations --> ImagingQualitativeEvaluation : contains[0..*]

ImagingMeasurementGroup --> ImagingMeasurement : hasMember[0..*]
ImagingMeasurementGroup --> ImagingQualitativeEvaluation : hasMember[0..*]
ImagingMeasurementGroup --> MeasurementGroupDevice : device[1..1]
ImagingMeasurementGroup --> EquipmentDevice : device[1..1]
ImagingMeasurementGroup .. MGNote
MGNote .. MeasurementGroupDevice
MGNote .. EquipmentDevice


ImagingMeasurement --> MeasurementDevice : device[1..1]
ImagingMeasurement --> EquipmentDevice : device[1..1]
ImagingMeasurement .. MNote
MNote .. MeasurementDevice
MNote .. EquipmentDevice

ImagingQualitativeEvaluation --> QualitativeDevice : device[1..1]
ImagingQualitativeEvaluation --> EquipmentDevice : device[1..1]
ImagingQualitativeEvaluation .. QENote
QENote .. QualitativeDevice
QENote .. EquipmentDevice


MeasurementDevice --> EquipmentDevice : parent[1..1]

MeasurementGroupDevice --> EquipmentDevice : parent[1..1]

QualitativeDevice --> EquipmentDevice : parent[1..1]

@enduml
