@startuml imaging_measurement_group_mapping
left to right direction

map inputs {
   subject => Patient
   partOf => ImagingStudy
   basedOn => ServiceRequest
   focus => ImagingSelection
   bodyStructure => FindingSite
   device => Algorithm Identification or EquipmentDevice
}

package "ImagingMeasurement" as imagingMeasurement {
   object "$Measurement" as measurement
   object "Measurement Method" as method
   object "Finding Site" as findingSite
   object "Algorithm Identification" as algorithm
}

object AlgorithmIdentification {
    parent = Algorithm Identification or EquipmentDevice
}

object FindingSite {
    includedStructure.structure = FindingSite
}

object "ImagingMeasurement" as imagingMeasurement {
    subject = Patient
    partOf = ImagingStudy
    basedOn = ServiceRequest
    device = EquipmentDevice or AlgorithmIdentification
    focus = TrackingBodyStructure
    focus = ImagingSelection
    bodyStructure = FindingSite
    code = Concept Name Code Sequence
    issued = Observation DateTime
    method = Measurement Method
    valueQuantity = Measured Value Sequence
}

algorithm --> AlgorithmIdentification: Create AlgorithmIdentification from Algorithm Identification content item
findingSite --> FindingSite: Create BodyStructure from Finding Site

inputs --> imagingMeasurement
AlgorithmIdentification --> imagingMeasurement
TrackingBodyStructure --> imagingMeasurement
FindingSite --> imagingMeasurement
ImagingSelection --> imagingMeasurement
method --> imagingMeasurementGroup

@enduml