@startuml imaging_measurements_mapping
left to right direction

map inputs {
   subject => Patient
   partOf => ImagingStudy
   basedOn => ServiceRequest
   device => EquipmentDevice
}

package "Imaging Measurements Container" as imagingMeasurementGroup {
   object "Algorithm Identification" as algorithm
   object "Measurement Group" as measurementGroup
   package "Derived Imaging Measurements" {
      object "Derived Imaging Measurement" as derivedMeasurement
   }
   package "Qualitative Evaluations" {
      object "Qualitative Evaluation" as qualitativeEvaluations
   }
}

object AlgorithmIdentification {
    parent = EquipmentDevice
}

algorithm --> AlgorithmIdentification: Create AlgorithmIdentification from Algorithm Identification content item

map measurementGroupMap {
    subject => Patient
    partOf => ImagingStudy
    basedOn => ServiceRequest
    device => AlgorithmIdentification or EquipmentDevice
}

map derivedMeasurementsMap {
    subject => Patient
    partOf => ImagingStudy
    basedOn => ServiceRequest
    device => AlgorithmIdentification or EquipmentDevice
}

map qualitativeEvaluationsMap {
    subject => Patient
    partOf => ImagingStudy
    basedOn => ServiceRequest
    device => AlgorithmIdentification or EquipmentDevice
}

inputs -> measurementGroupMap
inputs -> derivedMeasurementsMap
inputs -> qualitativeEvaluationsMap
measurementGroup --> measurementGroupMap: Map contents of Measurement Group Container
derivedMeasurement --> derivedMeasurementsMap: Map contents of Derived Measurements Container
qualitativeEvaluations -> qualitativeEvaluationsMap: Map contents of Qualitative Evaluations Container

@enduml