@startuml tid_1500_measurement_report
skinparam componentStyle rectangle
allowmixing
left to right direction

package "DICOM SR Measurement Report" as measurementReport {
    package "Document IE" as documentIE {
        package "SR Content Sequence" as srContentSequence {
            package "Imaging Measurements Container" as imagingMeasurementsContainer {
                package "0..* Measurements Group" as measurementsGroup {
                    object "0..* Numerical Measurement" as numericalMeasurement
                    object "0..* Qualitative Evaluation" as measurementGroupQualitativeEvaluation
                }
                package "0..* Derived Imaging Measurements" as derivedImagingMeasurements {
                    object "0..* Measurements Group" as derivedMeasurementsGroup
                }
                package "Qualitative Evaluations" as qualitativeEvaluations {
                    object "0..* Qualitative Evaluation" as qualitativeEvaluation
                }
            }
        }
    }
}

class "Imaging Measurement Group" as ImagingMeasurementGroup <<Observation>> #d5e8d4 ##green
class "Imaging Measurement" as ImagingMeasurement <<Observation>> #d5e8d4 ##green
class "Derived Imaging Measurement" as DerivedImagingMeasurement <<Observation>> #d5e8d4 ##green
class "Imaging Qualitative Evaluation" as ImagingQualitativeEvaluation <<Observation>> #d5e8d4 ##green

measurementsGroup -> ImagingMeasurementGroup : maps to
derivedMeasurementsGroup --> DerivedImagingMeasurement : maps to
qualitativeEvaluation --> ImagingQualitativeEvaluation : maps to

ImagingMeasurementGroup --> ImagingMeasurement : hasMember [0__*]
ImagingMeasurementGroup --> ImagingQualitativeEvaluation : hasMember [0__*]
DerivedImagingMeasurement --> ImagingMeasurementGroup : derivedFrom [0__*]
@enduml
