@startuml tid_1500_structure
left to right direction

package "TID 1500 Measurement Report" #EEEEEE {
    package "EV 126010 Imaging Measurements" {
    }
    package "EV 126011 Derived Imaging Measurements" {
    }
    package "EV C0034375 Qualitative Evaluations" {
    }
}
package "TID 1410 Planar ROI Measurements and Qualitative Evaluations" {
    package "EV 125007 Measurement Group (TID 1410)" {
    }
}
package "TID 1411 Volumetric ROI Measurements and Qualitative Evaluations" {
    package "EV 125007 Measurement Group (TID 1411)" {
    }
}
package "TID 1501 Measurement and Qualitative Evaluation Group" {
    package "EV 125007 Measurement Group (TID 1501)" {
    }
}
package "TID 1420 Measurements Derived From Multiple ROI Measurements" {
}
class measurementGroup as "Observation[imagingMeasurementGroup]"
class measurement as "Observation[imagingMeasurement]"
class qualitativeEvaluation as "Observation[imagingQualitativeEvaluation]"
class derivedMeasurement as "Observation[derivedImagingMeasurement]"

"EV 126010 Imaging Measurements" --> "TID 1410 Planar ROI Measurements and Qualitative Evaluations": Contains[0..*]
"EV 126010 Imaging Measurements" --> "TID 1411 Volumetric ROI Measurements and Qualitative Evaluations": Contains[0..*]
"EV 126010 Imaging Measurements" --> "TID 1501 Measurement and Qualitative Evaluation Group": Contains[0..*]
"EV 126011 Derived Imaging Measurements" --> "TID 1420 Measurements Derived From Multiple ROI Measurements": Contains[0..*]
"EV C0034375 Qualitative Evaluations" --> qualitativeEvaluation: Contains[0..*]
"EV 125007 Measurement Group (TID 1410)" --> measurementGroup: Contains[1..1]
"EV 125007 Measurement Group (TID 1411)" --> measurementGroup: Contains[1..1]
"EV 125007 Measurement Group (TID 1501)" --> measurementGroup: Contains[1..1]
measurementGroup --> measurement: Contains[0..*]
measurementGroup --> qualitativeEvaluation: Contains[0..*]
"TID 1420 Measurements Derived From Multiple ROI Measurements" --> derivedMeasurement: Contains[0..*]
derivedMeasurement --> measurementGroup: Derived From[0..*]
@enduml