# ╭─────────────────────────────────ImplementationGuide-fish.json──────────────────────────────────╮
# │  The properties below are used to create the ImplementationGuide resource. For a list of       │
# │  supported properties, see:                                                                    │
# │  https://fshschool.org/docs/sushi/configuration/#full-configuration                            │
# ╰────────────────────────────────────────────────────────────────────────────────────────────────╯
id: hl7.fhir.uv.dicom-sr
canonical: http://hl7.org/fhir/uv/dicom-sr
version: 1.0.0
name: DICOMSRToFHIRResourceMappingIG
title: DICOM® SR to FHIR Resource Mapping IG
status: draft
publisher: 
  - name: HL7 International / Imaging Integration
  - url: http://www.hl7.org/Special/committees/imagemgt
contact:
  - name: HL7 International / Imaging Integration
    telecom:
      - system: url
        value: http://www.hl7.org/Special/committees/imagemgt
  - name: Jonathan Whitby
    telecom:
      - system: email
        value: jonathan.whitby@mi.medical.canon
      - system: url
        value: http://www.hl7.org/Special/committees/imagemgt
  - name: Christopher Lindop
    telecom:
      - system: email
        value: Christopher.Lindop@ge.com
      - system: url
        value: http://www.hl7.org/Special/committees/imagemgt
description: Provides guidance for extracting key content from DICOM® Structured Report (SR) objects into FHIR Observations to make use of the results with  the larger hospital enterprise.
jurisdiction: "http://unstats.un.org/unsd/methods/m49/m49.htm#001"
license: CC0-1.0
fhirVersion: 5.0.0
copyrightYear: 2024+
releaseLabel: STU1 Ballot
dependencies:
  fhir.dicom:
    uri: http://fhir.org/packages/fhir.dicom
    version: 2025.2.20250411
parameters:
  show-inherited-invariants: false
  usage-stats-opt-out: true
  apply-contact: true
  apply-context: true
  apply-copyright: true
  apply-jurisdiction: true
  apply-license: true
  apply-publisher: true
  apply-version: true
  auto-oid-root: 2.16.840.1.113883.4.642.40.39

extension:
  - url: http://hl7.org/fhir/StructureDefinition/structuredefinition-wg
    valueCode: ii
pages:
  index.md:
    title: Home
    generation: markdown
  background.md:
    title: Background
    generation: markdown
  architecture.md:
    title: Architecture
    generation: markdown
  mapping.md:
    title: Mapping
    generation: markdown
  example.md:
    title: Example
    generation: markdown

# ╭────────────────────────────────────────────menu.xml────────────────────────────────────────────╮
# │  To use a provided input/includes/menu.xml file, delete the "menu" property below.             │
# ╰────────────────────────────────────────────────────────────────────────────────────────────────╯
menu:
  IG Home: index.html
  Contents: toc.html
  Background: background.html
  Architecture: architecture.html
  Mapping: mapping.html
  Example: example.html
  Artifact Index: artifacts.html
