# ╭─────────────────────────────────ImplementationGuide-fish.json──────────────────────────────────╮
# │  The properties below are used to create the ImplementationGuide resource. For a list of       │
# │  supported properties, see:                                                                    │
# │  https://fshschool.org/docs/sushi/configuration/#full-configuration                            │
# ╰────────────────────────────────────────────────────────────────────────────────────────────────╯
id: hl7.fhir.uv.dicom-sr
canonical: http://hl7.org/fhir/dicom-sr
version: 0.1.0
name: DICOMSRToFHIRResourceMappingIG
title: DICOM SR to FHIR Resource Mapping IG
status: draft
publisher: 
  - name: HL7 Imaging Integration Working Group
  - url: http://www.hl7.org/Special/committees/imagemgt/index.cfm
contact:
  - name: HL7 Imaging Integration Workgroup
    telecom:
      - system: url
        value: http://www.hl7.org/Special/committees/imagemgt/index.cfm
  - name: Jonathan Whitby
    telecom:
      - system: email
        value: jonathan.whitby@mi.medical.canon
  - name: Christopher Lindop
    telecom:
      - system: email
        value: Christopher.Lindop@ge.com
description: Provides guidance for extracting key content from DICOM Structured Report (SR) objects into FHIR Observations  to make use of the results with  the larger hospital enterprise. 
jurisdiction: "http://unstats.un.org/unsd/methods/m49/m49.htm#001"
license: CC0-1.0
fhirVersion: 5.0.0-snapshot3
dependencies:
parameters:
  show-inherited-invariants: false
  generate-turtle: false
  usage-stats-opt-out: true
copyrightYear: 2020+
releaseLabel: ci-build

pages:
  index.md:
    title: Home
    generation: markdown
  background.md:
    title: Background
    generation: markdown
  architecture.md:
    title: Architecture
    generation: markdown


# ╭────────────────────────────────────────────menu.xml────────────────────────────────────────────╮
# │  To use a provided input/includes/menu.xml file, delete the "menu" property below.             │
# ╰────────────────────────────────────────────────────────────────────────────────────────────────╯
menu:
  IG Home: index.html
  Contents: toc.html
  Background: background.html
  Architecture: architecture.html
  Artifact Index: artifacts.html
